### ISSUE TITLE
Consider checkpointing HexSumTree every term

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-court#11]
Currently the HexSumTree is a singleton-type object which we only modify in the `heartbeat()` function so the state of the tree stays constant during the term allowing deterministic juror drafts throughout the term. This comes with the following drawbacks:

- Because all modifications to the tree are batched for the `heartbeat()` of a future term, we need to limit how many mutations can be performed in a given term to avoid `heartbeat()` to require more gas than the block gas limit and bricking the court.

- Disputes need to draft their jurors strictly during the correct term because the juror sum tree can mutate in the transition to the next term. If the jurors of a dispute aren't drafted during the term, the dispute needs to be rescheduled for a future term.

By checkpointing the state of the tree every term we would be able to:

- Immediately perform tree modifications for the **next** term, no longer scheduling modifications to a future term's `heartbeat()`.

- Draft jurors for a dispute at any term in the future, as the drafting function would be able to perform sortition on a past state of the tree.

- Being able to prove to a contract how many tokens a juror had active and for how long, which would be really useful for distributing passive rewards (as discussed in #9)

Downsides:

- Gas cost:

  - I am particularly worried about the added `SLOAD` cost while traversing the tree performing a sortition, as for every node in the tree we'd need to get its checkpointed value (even though it is a binary search, it would increase the number `SLOAD`s by at least a factor of 2 and grows logarithmically with the number of balance updates of a juror has had).

  - The `SSTORE` cost for modifying tree entries wouldn't be that different for trees of a reasonable size specially taking into account that the Court would no longer have to manage queues in storage. The `SSTORE` overhead would be an extra `~20k * log16(N)` (`N` being the number of jurors) in the worst case (the first update for the next term), which would add up to an extra ~100k gas for a tree of ~1.04M (`16 ^ 5`) jurors. A positive side-effect is that this gas would be paid by the juror directly in almost all instances.

- Removing the requirement to draft an adjudication round during an specific term, presents some challenges of its own with the current design:
  - Deferred juror unstaking: because at the time drafting can only happen during one specific term and adjudication rounds that fail to draft on time need to be rescheduled, the moment a juror is deactivated we know exactly how many tokens they have at stake (and we can allow them to withdraw all their tokens that aren't at risk of being slashed). If an adjudication round no longer needs to be drafted during an specific term, we'd need to prevent the juror from unstaking for at least the duration of a full adjudication round (commit + reveal + appeal) which is a reasonable time span for cancelling/rescheduling the round if the draft didn't happen.

  - Higher risk of missing block hashes: the block hash used as a randomness seed for a term needs to be queried and saved within 257 blocks after the term is transitioned. If a round no longer needs to be drafted within the term, we may need to add an extra incentive to perform a secondary `hearbeat()` to store the randomness seed for all terms with adjudication rounds.

- Scheduling: at the moment, jurors can schedule their activation and deactivation to a custom term. This is a nice side-effect of not being able to perform activations immediately, as we don't care whether a modification happens in the next term because it needs to be scheduled anyway. If we were to add checkpointing, we'd likely remove the ability to schedule activations and deactivations.

**Comment by bingen** [comment]
Some numbers from my first tests:

# Without Checkpointing:
## inserts one node (172ms)
Tree depth:    1
Tree next key: 1
Insert gas: 85080 (-> Remix: 64466)
Sortition 5 gas: 23543

## inserts a few consecutive nodes (12852ms)
Tree depth:    3
Tree next key: 270
Inserts
Size:    270

|         |  Total |  - 21k |
|---------|--------|--------|
| Min     |  55080 |  34080 |
| Max     | 122379 | 101379 |
| Average |  62076 |  41076 |

Sortition 2605 gas: 35129


## lots of activity (128627ms)
Tree depth:    3
Tree next key: 2304
Inserts
Size:    2304
|         |  Total |  - 21k |
|---------|--------|--------|
| Min     |  55080 |  34080 |
| Max     | 122379 | 101379 |
| Average |  67001 |  46001 |
Removes
Size:    216
|         |  Total |  - 21k |
|---------|--------|--------|
| Min     |  40226 |  19226 |
| Max     |  46160 |  25160 |
| Average |  45507 |  24507 |
Sortitions
Size:    216
|         |  Total |  - 21k |
|---------|--------|--------|
| Min     |  25176 |   4176 |
| Max     |  40380 |  19380 |
| Average |  33022 |  12022 |


## lots of activity, batched (99320ms)
Tree depth:    4
Tree next key: 4160
Inserts
Size:    65
|         |  Total |  - 21k |
|---------|--------|--------|
| Min     |  39544 |  39215 |
| Max     |  52812 |  52484 |
| Average |  45942 |  45614 |
Removes
Size:    65
|         |  Total |  - 21k |
|---------|--------|--------|
| Min     |  26121 |  22621 |
| Max     |  33874 |  30374 |
| Average |  28930 |  25430 |
Sortitions
Size:    195
|         |  Total |  - 21k |
|---------|--------|--------|
| Min     |  26744 |   5744 |
| Max     |  40480 |  19480 |
| Average |  34088 |  13088 |


## forcing (fake) big tree (17111ms)
Tree depth:    8
Tree next key: 268435726
Inserts
Size:    270
|         |  Total |  - 21k |
|---------|--------|--------|
| Min     |  92379 |  71379 |
| Max     | 125631 | 104631 |
| Average |  96847 |  75847 |
Sortition 2605 gas: 40880

## inserts a lot of times into the first node (7382ms)
Tree depth:    1
Tree next key: 1
Sets
Size:    200
|         |  Total |  - 21k |
|---------|--------|--------|
| Min     |  35072 |  14072 |
| Max     |  35072 |  14072 |
| Average |  35072 |  14072 |
Sortition 0 gas: 23479


## inserts a lot of times into a middle node (21113ms)
Tree depth:    3
Tree next key: 270
Inserts
Size:    270
|         |  Total |  - 21k |
|---------|--------|--------|
| Min     |  55080 |  34080 |
| Max     | 122379 | 101379 |
| Average |  62076 |  41076 |
Sets
Size:    200
|         |  Total |  - 21k |
|---------|--------|--------|
| Min     |  46722 |  25722 |
| Max     |  46722 |  25722 |
| Average |  46722 |  25722 |
Sortition 2605 gas: 37911

# With Checkpointing
## inserts one node (225ms)
Tree depth:    1
Tree next key: 1
Insert gas: 129248
Sortition 5 gas: 24990

## inserts a few consecutive nodes (16345ms)
Tree depth:    3
Tree next key: 270
Inserts
Size:    270
|         |  Total |  - 21k |
|---------|--------|--------|
| Min     | 100577 |  79577 |
| Max     | 213574 | 192574 |
| Average | 130286 | 109286 |
Sortition 2605 gas: 34011

## lots of activity (180776ms)
Tree depth:    3
Tree next key: 2304
Inserts
Size:    2304
|         |  Total |  - 21k |
|---------|--------|--------|
| Min     | 100577 |  79577 |
| Max     | 213574 | 192574 |
| Average | 155608 | 134608 |
Removes
Size:    216
|         |  Total |  - 21k |
|---------|--------|--------|
| Min     | 109260 |  88260 |
| Max     | 138144 | 117144 |
| Average | 134941 | 113941 |
Sortitions
Size:    216
|         |  Total |  - 21k |
|---------|--------|--------|
| Min     |  28889 |   7889 |
| Max     |  76328 |  55328 |
| Average |  47259 |  26259 |

## lots of activity, batched (166135ms)
Tree depth:    4
Tree next key: 4160
Inserts
Size:    65
|         |  Total |  - 21k |
|---------|--------|--------|
| Min     |  68952 |  68624 |
| Max     |  89741 |  89413 |
| Average |  79307 |  78979 |
Removes
Size:    65
|         |  Total |  - 21k |
|---------|--------|--------|
| Min     |  58125 |  54625 |
| Max     |  82545 |  79045 |
| Average |  70648 |  67148 |
Sortitions
Size:    195
|         |  Total |  - 21k |
|---------|--------|--------|
| Min     |  32726 |  11726 |
| Max     |  85477 |  64477 |
| Average |  51546 |  30546 |

## forcing (fake) big tree (31952ms)
Tree depth:    8
Tree next key: 268435726
Inserts
Size:    270
|         |  Total |  - 21k |
|---------|--------|--------|
| Min     | 204032 | 183032 |
| Max     | 334756 | 313756 |
| Average | 301949 | 280949 |
Sortition 2605 gas: 42113

## inserts a lot of times into the first node (14560ms)
Tree depth:    1
Tree next key: 1
Sets
Size:    200
|         |  Total |  - 21k |
|---------|--------|--------|
| Min     |  81854 |  60854 |
| Max     |  81854 |  60854 |
| Average |  81854 |  60854 |
Sortitions
Size:    200
|         |  Total |  - 21k |
|---------|--------|--------|
| Min     |  25986 |   4986 |
| Max     |  32108 |  11108 |
| Average |  31881 |  10881 |

## inserts a lot of times into a middle node (64829ms)
Tree depth:    3
Tree next key: 270
Inserts
Size:    270
|         |  Total |  - 21k |
|---------|--------|--------|
| Min     | 100577 |  79577 |
| Max     | 213574 | 192574 |
| Average | 130286 | 109286 |
Sets
Size:    200
|         |  Total |  - 21k |
|---------|--------|--------|
| Min     | 139346 | 118346 |
| Max     | 139346 | 118346 |
| Average | 139346 | 118346 |
Sortitions
Size:    200
|         |  Total |  - 21k |
|---------|--------|--------|
| Min     |  84139 |  63139 |
| Max     | 103191 |  82191 |
| Average | 102646 |  81646 |

# Debugging storage
Some of these numbers looked kind of weird to me, so I tried with Remix, inserting 1 or 3 nodes. For some reason, Truffle numbers were higher.
For such a small numbers, the extra storage due to the initial slot of the array has big impact. With repeated updated on a node that impact will be diluted, but the difference will be of course higher.

## Without Checkpointing
### One node
![remix_straight_1](https://user-images.githubusercontent.com/701095/55197634-71b20a00-51b3-11e9-92e0-9c3dee6cfb44.png)
### Three nodes
![remix_straight_3](https://user-images.githubusercontent.com/701095/55197651-78d91800-51b3-11e9-9681-ed7fe08fdb42.png)

## With Checkpointing
### One node
![remix_checkpoint_1](https://user-images.githubusercontent.com/701095/55197673-8d1d1500-51b3-11e9-9e56-c9d9b53af620.png)
### Three nodes
![remix_checkpoint_3](https://user-images.githubusercontent.com/701095/55197686-90b09c00-51b3-11e9-831f-31445ce9b2d5.png)

# Other considerations
- Although most of the time jurors will pay for the extra gas on updating values, it won't be the case when fees are redistributed and balances updated.
- The higher a node in the tree, the more often it will be updated. For instance, the root node will be updated every single time any balance of any juror is updated. The checkpointing array for these high nodes could grow too big.
