### ISSUE TITLE
Audit: Process deactivation requests when going through staking interface

### ISSUE THREAD

**Issue by facuspagnuolo** [aragon/aragon-court#229]
Code recommendations 10: (report [reference](https://docs.google.com/document/d/1c7rEDCzJLuaxq5FHRRxYZ09rqityk9kcOOyPyfKLgbI/edit#heading=h.b8w8rtsbux00))

**Comment by bingen** [comment]
Actually the two things are independent: the minimum active balance refers to what there's in the tree, which is updated in the tree in the deactivation function (scheduled for next term though). What is left pending is the **available** balance (because we don't have (future) checkpointing for those balances). So the minimum active balance is always correctly checked (except for the fact that min active balance was being fetched for current term instead of next term) and this is not an issue. But I agree is kind of inconsistent so I will move that call anyway.
