### ISSUE TITLE
Charge jurors a fee for the activation and deactivation term heartbeats

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-court#7]

**Comment by willjgriff** [comment]
Should the activation + deactivation fee be taken at the same time in the activate() function? Since the deactivate function may or may not be called and it's simpler than doing it in the heartbeats queue processing. And the fee could be returned to them in the deactivate function if it's called before the juror is activated. 

Also should any work on this also include payout of these fees to the heartbeat caller? To avoid discrepancies in the contracts total balance.

**Comment by bingen** [comment]
@izqui we can close this on, right?
